spring.application.name=logistica-back

#spring.datasource.url=jdbc:mysql://localhost:3307/db_donaton
spring.datasource.url=jdbc:mysql://database:3306/db_donaton
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Swagger
pringdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# puerto del microservicio
server.port=3003

# gateway
server.forward-headers-strategy=framework

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
